### ISSUE TITLE
Data Storage Service

### ISSUE THREAD

**Issue by yangroro** [yangroro/cloud-studyjam-intermediate#2]
k8s 구조에서 Data storage service는 EBS같은 외부 서비스를 쓰는건지 아니면 k8s에서 생성하는가?

**Comment by yangroro** [comment]
https://kubernetes.io/docs/concepts/storage/#local

**Comment by antiline** [comment]
https://blog.naver.com/PostView.nhn?blogId=alice_k106&logNo=221348788068&parentCategoryNo=&categoryNo=&viewDate=&isShowPopularPosts=false&from=postView

이런글도 있습니다.
