### ISSUE TITLE
Configmap과 Secret의 저장 위치

### ISSUE THREAD

**Issue by yangroro** [yangroro/cloud-studyjam-intermediate#3]
Configmap과 Secret은 Master에서 관리하는건지

**Comment by yangroro** [comment]
https://kubernetes.io/docs/concepts/configuration/secret/#risks 
etcd에 저장한다

**Comment by jeongukjae** [comment]
다시 살펴보면서 정리하는 중인데 secret을 api server에서만 etcd에 저장하고 Kubelet에서는 `tmpfs`에 저장하네요.

https://kubernetes.io/docs/concepts/configuration/secret/#protections
