### ISSUE TITLE
Canary 배포를 디테일하게 설정하려면? 외

### ISSUE THREAD

**Issue by imkitae** [yangroro/cloud-studyjam-intermediate#7]
### Canary 배포를 디테일하게 설정하려면?
튜토리얼에서 설정하는 canary 배포는 단순히 replica 숫자 비율로 확률이 결정되는데, 다른 방법은 없을까?

### readiness probe와 liveness probe
두 기능의 차이는 무엇인지?

**Comment by yangroro** [comment]
https://kubernetes.io/ko/docs/concepts/workloads/pods/pod-lifecycle/
